ApartmentRentals/ApartmentRentals/Controllers/UserController.cs
using ApartmentRentals.Model;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using Microsoft.Owin.Security;
using ApartmentRentals.BL;

namespace ApartmentRentals.Controllers
{
    public class UserController : Controller
    {
        IUserService _userService;
        public UserController(IUserService userService)
        {
            _userService = userService;
        }
        // GET: User
        public ActionResult Index()
        {
            return View();
        }

        // GET: User/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: User/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: User/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: User/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: User/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: User/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: User/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
        [Authorize(Roles = "Owner, Tenant")]
        [HttpPost]
        public ActionResult Message(MessageDTO message)
        {
            try
            {
                message.Date = DateTime.Now;
                _userService.AddMessage(message);
                return RedirectToAction("Index","Apartments");
            }
            catch
            {
                return View();
            }
        }
         [Authorize(Roles = "Owner, Tenant")]
        public ActionResult Messages()
        { 
            var list=_userService.GetAllConversations(User.Identity.GetUserId());
             return View(list);
        }
         [Authorize(Roles = "Owner, Tenant")]
        public ActionResult Offers()
        {
            var list = _userService.GetAllOffers(User.Identity.GetUserId());
            return View(list);
        }
         [Authorize(Roles = "Owner, Tenant")]
        [HttpPost]
        public ActionResult Conversation(MessageDTO message)
        {
            try
            {
                return View(_userService.GetConversation(message.Sender_Id,message.Receiver_Id).OrderByDescending(d=>d.Date));
            }
            catch
            {
                return View();
            }
        }

    }
}

ApartmentRentals/ApartmentRentals/Views/User/Conversation.cshtml
@model IEnumerable<ApartmentRentals.Model.MessageDTO>

@{
    ViewBag.Title = "Conversation";
}

<h2>Conversation</h2>
<p>
    @using Microsoft.AspNet.Identity;
    @using (Html.BeginForm("Message", "User", FormMethod.Post))
    {

        <input type="hidden" value="@User.Identity.GetUserId()" name="Sender_Id" />
        if (Model.First().Receiver_Id.Equals(@User.Identity.GetUserId()))
        {

            <input type="hidden" value="@Model.First().Sender_Id" name="Receiver_Id" />
        }
        else
        {
            <input type="hidden" value="@Model.First().Receiver_Id" name="Receiver_Id" />
        }
        <textarea name="Description" required></textarea>
        <input type="submit" value="Send new message" class="btn btn-default" />
    }

</p>
<table class="table">
    <tr>
        <th>
            Sender
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Date)
        </th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.AspNetUser.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Date)
            </td>
        </tr>
    }

</table>

ApartmentRentals/ApartmentRentals/Views/User/Messages.cshtml
@model IEnumerable<ApartmentRentals.Model.UserDTO>

@{
    ViewBag.Title = "Messages";
}

<h2>Messages</h2>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)

        </th>
 
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>@using Microsoft.AspNet.Identity;
            @using(Html.BeginForm("Conversation", "User", FormMethod.Post))
            {
                    <input type="hidden" value="@User.Identity.GetUserId()" name="Sender_Id" />
                    <input type="hidden" value="@item.Id" name="Receiver_Id" />
                    <input type="submit" value="See conversation" class="btn btn-default" />
            }
        </td>
    </tr>
}

</table>

ApartmentRentals/ApartmentRentals/Views/User/Offers.cshtml
@model IEnumerable<ApartmentRentals.Model.OfferDTO>

@{
    ViewBag.Title = "Offers";
}

<h2>Offers</h2>

<table class="table">
    <tr>
        <th>
            Apartment Id
        </th>
        <th>
            Fee
        </th>
        <th>
            Date
        </th>
        <th>
            Status
        </th>
        <th>
            Response
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Apartment.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Fee) $
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Date)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Status_Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Response)
            </td>
            <td>
                @using Microsoft.AspNet.Identity;
                @if (Request.IsAuthenticated && User.IsInRole("Owner") && item.Status_Id.Equals("Sent"))
                {
                    using (Html.BeginForm("Accept", "Apartments", FormMethod.Post))
                    {
                        <input type="hidden" value="@item.Id" name="Id" />
                        <input type="hidden" value="@item.Apartment_Id" name="Apartment_Id" />

                        <input type="submit" value="Accept" class="btn btn-default" style="display:inline" />
                    }
                    using (Html.BeginForm("Refuse", "Apartments", FormMethod.Post))
                    {
                        <input type="hidden" value="@item.Id" name="Id" />
                        <input type="hidden" value="@item.Apartment_Id" name="Apartment_Id" />
                        <input type="text" name="Response" style="display:inline" />
                        <input type="submit" value="Refuse" class="btn btn-default" style="display:inline" />
                    }
                }
            </td>
        </tr>
    }

</table>