BookStore/BookStore/Controllers/BookController.cs
using BookStore.Models;
using BookStore.Models.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagedList;
using BookStore.App_Start;
using Bookstore.DataAccess;
namespace BookStore.Controllers
{
    
    public class BookController : Controller
    {
        IBookUnitOfWork _BookUnitOfWork;
        public BookController(IBookUnitOfWork bookUoW)
        {
            _BookUnitOfWork = bookUoW;
        }

        [CustomAuthorization(IdentityRoles = "Regular_User,Admin")]
        // GET: Book
        public ActionResult Index(int page=1,int pageSize=10)
        {

            List<BookViewModel> booksToDisplay = _BookUnitOfWork.GetAll().ToList();
            ViewBag.SearchText = "";
            ViewBag.SearchOption = 0;
            return View(booksToDisplay.ToPagedList(page,10));
        }
        [CustomAuthorization(IdentityRoles = "Regular_User,Admin")]
        // GET: Book/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }
       
        // GET: Book/Create
         [CustomAuthorization(IdentityRoles = "Admin")]
        public ActionResult Create()
        {
            return View();
        }

        // POST: Book/Create
        [CustomAuthorization(IdentityRoles = "Admin")]
        [HttpPost]
        public ActionResult Create(BookViewModel book)
        {
            try
            {

                _BookUnitOfWork.Create(book);

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Book/Edit/5
        [CustomAuthorization(IdentityRoles = "Admin")]
        public ActionResult Edit(int id)
        {
            BookViewModel book = _BookUnitOfWork.GetById(id);
            if (book == null)
            {
                return RedirectToAction("Index");
            }
        
            return View(book);
        }

        // POST: Book/Edit/5
        [CustomAuthorization(IdentityRoles = "Admin")]
        [HttpPost]
        public ActionResult Edit(BookViewModel book)
        {
            try
            {
                // TODO: Add update logic here
                _BookUnitOfWork.Update(book);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        //// GET: Book/Delete/5
        [CustomAuthorization(IdentityRoles = "Admin")]
        public ActionResult Delete(int id)
        {
            BookViewModel book = _BookUnitOfWork.GetById(id);
            if (book == null)
            {
                return RedirectToAction("Index");
            }
            return View(book);
        }

        // POST: Book/Delete/5
        [CustomAuthorization(IdentityRoles = "Admin")]
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            _BookUnitOfWork.Delete(id);
            return RedirectToAction("Index");
        }

        [CustomAuthorization(IdentityRoles = "Regular_User,Admin")]
        public ActionResult Search(String searchText = "", int searchOption = 0, int page = 1)
        {
            List<BookViewModel> books = new List<BookViewModel>();

            switch (searchOption)
            {
                case 0:
                    books.AddRange(_BookUnitOfWork.SearchByTitle(searchText).ToList());
                    break;
                case 1:
                    books.AddRange(_BookUnitOfWork.SearchByAuthor(searchText).ToList());
                    break;
                case 2:
                    books.AddRange(_BookUnitOfWork.SearchByGenre(searchText).ToList());
                    break;
            }
            ViewBag.SearchText = searchText;
            ViewBag.SearchOption = searchOption;
            return View("Index", books.ToPagedList(page, 10));
        }
        [CustomAuthorization(IdentityRoles = "Regular_User,Admin")]
        public ActionResult Sell(int id)
        {
            BookViewModel book = _BookUnitOfWork.GetById(id);
            return View(book);
        }
        
        [HttpPost]
        [CustomAuthorization(IdentityRoles = "Regular_User,Admin")]
        public ActionResult Sell(BookViewModel book)
        {
            _BookUnitOfWork.Sell(book);
            return RedirectToAction("Index");
        }
        [CustomAuthorization(IdentityRoles = "Admin")]
        public ActionResult GenerateCSV()
        {
            String fileName=_BookUnitOfWork.GenerateReport("csv");
             System.Web.HttpResponse response = System.Web.HttpContext.Current.Response;
        response.ClearContent();
        response.Clear();
        response.ContentType = "text/plain";
        response.AddHeader("Content-Disposition", 
                           "attachment; filename=" + fileName + ";");
        response.TransmitFile(fileName);
        response.Flush();    
        response.End();
            return RedirectToAction("Index");
        }
        [CustomAuthorization(IdentityRoles = "Admin")]
        public ActionResult GeneratePDF()
        {
            String fileName = _BookUnitOfWork.GenerateReport("pdf");
            System.Web.HttpResponse response = System.Web.HttpContext.Current.Response;
            response.ClearContent();
            response.Clear();
            response.ContentType = "text/plain";
            response.AddHeader("Content-Disposition",
                               "attachment; filename=" + fileName + ";");
            response.TransmitFile(fileName);
            response.Flush();
            response.End();
            return RedirectToAction("Index");
        }

    }
}

BookStore/BookStore/Views/Book/Create.cshtml
@model BookStore.Models.ViewModels.BookViewModel

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>BookViewModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Author, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Author, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Author, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Genre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Genre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Genre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Quantity, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Quantity, new { htmlAttributes = new { @class = "form-control",min=0 } })
                @Html.ValidationMessageFor(model => model.Quantity, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control",min=0 } })
                @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

BookStore/BookStore/Views/Book/Delete.cshtml
@model BookStore.Models.ViewModels.BookViewModel

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>BookViewModel</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Author)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Author)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Genre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Genre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Quantity)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Quantity)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

BookStore/BookStore/Views/Book/Edit.cshtml
@model BookStore.Models.ViewModels.BookViewModel

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>BookViewModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Author, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Author, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Author, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Genre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Genre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Genre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Quantity, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Quantity, new { htmlAttributes = new { @class = "form-control",min=0 } })
                @Html.ValidationMessageFor(model => model.Quantity, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control",min=0 } })
                @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

BookStore/BookStore/Views/Book/Index.cshtml
@model IPagedList<BookStore.Models.ViewModels.BookViewModel>

@{
    ViewBag.Title = "Index";
    var user=Session["user"] as BookStore.Models.User;
}

<h2>Index</h2>
@using (Html.BeginForm("Search","Book"))
 {
    @Html.TextBox("searchText")
    <input type="submit" id="searchButton" name="searchButton" value="Search" class="btn-default" />
    @Html.RadioButton("searchOption", 0, true);
    <text> By Title</text>
    @Html.RadioButton("searchOption", 1, false);
    <text> By Author</text>
    @Html.RadioButton("searchOption", 2, false);
    <text> By Genre</text>
 }
@if (user != null)
{
    if (user.Roles.Contains("Admin"))
    {
        <p>
            @Html.ActionLink("Create New", "Create")
        </p>
        <p>
            @Html.ActionLink("Generate PDF report", "GeneratePDF")
        </p>
        <p>
            @Html.ActionLink("Generate CSV report", "GenerateCSV")
        </p>
    }

}

@Html.Partial("_Books",Model)


<script type="text/javascript">
    $(document).ready(function () {

        $("#searchButton").click(function() {
            var search = {};
            user.Text = $("#searchText").val();
            user.Option = $("#searchOption").val();
            $.ajax({
                type: "POST",
                url: "/Book/Search",
                data: '{search: ' + JSON.stringify(search) + '}',
                contentType: "application/json; charset=utf-8",
                dataType: "json",
                success: function (response) {
                    alert("Search has been made.");
                }
            });
            return false;
        });
    });
</script>

BookStore/BookStore/Views/Book/Sell.cshtml
@model BookStore.Models.ViewModels.BookViewModel

@{
    ViewBag.Title = "Sell";
}

<h2>Sell</h2>

<div>
    <h4>BookViewModel</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Author)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Author)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Genre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Genre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Quantity)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Quantity)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>

    </dl>
    @using (Html.BeginForm("Sell", "Book", FormMethod.Post))
{
        @Html.HiddenFor(model => model.Id)

    <div class="form-group">
        @Html.LabelFor(model => model.Quantity, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Quantity, new { htmlAttributes = new { @class = "form-control", min = 1, max = Model.Quantity } })
            @Html.ValidationMessageFor(model => model.Quantity, "", new { @class = "text-danger"})
        </div>
    </div>
    <button type="submit">Sell</button>
}
</div>
<p>
    @Html.ActionLink("Back to List", "Index")
</p>

BookStore/BookStore/Views/Book/_Books.cshtml
@model IPagedList<BookStore.Models.ViewModels.BookViewModel>
@{
    var user=Session["user"] as BookStore.Models.User;
}
<table class="table" id="searchResults">
    <tr>
        <th>
            Title
        </th>
        <th>
            Author
        </th>
        <th>
            Genre
        </th>
        <th>
            Quantity
        </th>
        <th>
            Price
        </th>
        <th></th>
    </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Title)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Author)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Genre)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Quantity)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Price)
                </td>
                <td>
                    @if (item.Quantity > 0)
                    {
                        @Html.ActionLink("Sell", "Sell", new { id = item.Id })                        
                    }
                    
                    @if (user != null)
                    {

                        if (user.Roles.Contains("Admin"))
                        {
                            if (item.Quantity > 0)
                            {
                                <text> |</text>
                            }
                        @Html.ActionLink("Edit", "Edit", new { id = item.Id })
                         <text> |</text>
                        @Html.ActionLink("Delete", "Delete", new { id = item.Id })
                    }
                    }
                </td>
            </tr>
        }
</table>
<div class="pagedList" data-otf-target="#bookList">
    @Html.PagedListPager(Model, page => Url.Action("Search", new { searchText=ViewBag.SearchText, searchOption=ViewBag.SearchOption,page }), PagedListRenderOptions.ClassicPlusFirstAndLast)
</div>